authors:
  ChenKS:
    name: ChenKS
    description: SASTer
    avatar: https://aliyun.sastimg.mxte.cc/images/2023/12/17/QQ20220819164336a533d1c9c523e00b.th.jpg
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  陈汤林:
    name: 陈汤林
    description: SASTer
    avatar: https://aliyun.sastimg.mxte.cc/images/2023/12/17/QQ20220819164336a533d1c9c523e00b.th.jpg
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  Offensive77:
    name: Offensive77
    description: SASTer
    avatar: https://aliyun.sastimg.mxte.cc/images/2023/12/17/QQ20220819164336a533d1c9c523e00b.th.jpg
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  Jisu-Woniu:
    name: Jisu-Woniu
    description: SASTer
    avatar: https://aliyun.sastimg.mxte.cc/images/2023/12/17/QQ20220819164336a533d1c9c523e00b.th.jpg
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  linyuqi9:
    name: linyuqi9
    description: SASTer
    avatar: https://aliyun.sastimg.mxte.cc/images/2023/12/17/QQ20220819164336a533d1c9c523e00b.th.jpg
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  multicoloredstone:
    name: multicoloredstone
    description: SASTer
    avatar: https://aliyun.sastimg.mxte.cc/images/2023/12/17/QQ20220819164336a533d1c9c523e00b.th.jpg
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  EnderHorror:
    name: EnderHorror
    description: SASTer
    avatar: https://aliyun.sastimg.mxte.cc/images/2023/12/17/QQ20220819164336a533d1c9c523e00b.th.jpg
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  Brethland Yang:
    name: Brethland Yang
    description: SASTer
    avatar: https://aliyun.sastimg.mxte.cc/images/2023/12/17/QQ20220819164336a533d1c9c523e00b.th.jpg
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  J.C:
    name: J.C
    description: SASTer
    avatar: https://aliyun.sastimg.mxte.cc/images/2023/12/17/QQ20220819164336a533d1c9c523e00b.th.jpg
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  xjzsq:
    name: xjzsq
    description: SASTer
    avatar: https://aliyun.sastimg.mxte.cc/images/2023/12/17/QQ20220819164336a533d1c9c523e00b.th.jpg
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  Serein:
    name: Serein
    description: SASTer
    avatar: https://avatars.githubusercontent.com/u/118594118
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  RdQuQu:
    name: rdququ
    description: SASTer
    avatar: https://rdququ.top/images/avatar.png
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
  NONE:
    name: 匿名
    description: SASTer
    avatar: https://aliyun.sastimg.mxte.cc/images/2023/12/17/QQ20220819164336a533d1c9c523e00b.th.jpg
    slug: url           # Author profile slug
    url: https://wiki.sast.fun            # Author website URL
