on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install mkdocs
        run: pip install mkdocs-material

      - uses: actions/checkout@v3
         with:
           fetch-depth: 0

      - name: Test
        run: bash test.sh
