on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install mkdocs
        run: pip install mkdocs-material

      - name: Test
        run: |
          pwd
          ls
          bash test.sh
